#ifndef CONF_H
#define CONF_H

#define REQUEST_LENGTH 500
#define RESPONSE_LENGTH 500
#define MAX_CONNS 10
#define PORT 1337
#define SOCKET_BACKLOG_SIZE 2
#define VALUES_PER_HEADER 10
#define STRING_VALUE_LENGTH 32
#define DOMAIN_LENGTH 50
#define PATH_LENGTH 128

#endif
